# Generated by Django 2.1 on 2018-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='prince',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.IntegerField(choices=[(1, 'lenovo'), (2, 'msi'), (3, 'asus'), (4, 'hp')], default=2),
        ),
    ]
